language: php

php:
  - 7.0
  - nightly

sudo: false

before_script:
  - php -r "file_exists('.env') || copy('.env.example', '.env');"
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev
  - php artisan key:generate

before_script:


script:
  - vendor/bin/phpunit --exclude-group=integrations

notifications:
  email:
    recipients:
      # hello@handesk.io
    on_success: never
    on_failure: always
